name = "manga-admin"
type = "javascript"

[env.production]
vars = { NODE_VERSION = "24" }
name = "manga-admin-production"

[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "modules"
main = "./.cloudflare/worker.js"

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.js", "**/*.css"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[env.production]
vars = { 
  NODE_VERSION = "24"
}

[env.production.secrets]
NEXT_PUBLIC_SUPABASE_URL = "https://bdbpkmvxnbyaykfxbnft.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "oEz8e5NLLLOGA6TNKVs2YD0JXnF98Zu7DrztmO7ndXprNiHtc6by1N6TKV04C7i2qJkVn16yWy+6Frl3InfmOg=="
SUPABASE_SERVICE_ROLE_KEY = "sb_secret_LYAxjT6rXJzj5ek-BCbgxg_-XIRHzTn"

